### ISSUE TITLE
Readability of errors on registration form

### ISSUE THREAD

**Issue by ahtotruu** [ACCUConf/ACCUConf_Submission_Web_Application#48]
Could we make the validation errors on the registration form stand out a bit more? As it is now (see the attached screenshot), they are too easy to miss and this could leave people confused as to why nothing seems to be happening when they click the "Register" button.
![image](https://user-images.githubusercontent.com/720294/29636766-95736dae-885a-11e7-86fa-2ab65b0c0f3b.png)

**Comment by russel** [comment]
Commit d2292a84beb15f7f8bcdf3056e063e9c151dd936 changes the alert texts to red and the help texts to orange, does this work?

**Comment by ahtotruu** [comment]
Looks good to me. Closing issue.
