### ISSUE TITLE
Misleading password validation message

### ISSUE THREAD

**Issue by ahtotruu** [ACCUConf/ACCUConf_Submission_Web_Application#49]
Apparently there are some password complexity requirements in place that the word "test" does not meet, but
a) the requirements are not visible to users, and
b) the error message is highly misleading, leaving the user with the impression the two copies of the password do not match (which is not the case on the screenshot below, assuming copy-paste still works in my browser)
![image](https://user-images.githubusercontent.com/720294/29637063-968b4008-885b-11e7-95af-9414dfd53e36.png)

**Comment by russel** [comment]
The only constraint is that the passphrase is more than 8 characters, there are no other constraints. I failed to give users any hint at this! I have added a notice in the passphrase default text. cf. commit a0ca60ff2c89f6c30f022418ce1176e64900e3a6

**Comment by ahtotruu** [comment]
Confirmed, the hint is there now. Would still recommend to attach the validation check (and corresponding error message) to the first password field and have the second one check only that the password confirmation matches the first entry (and show and error only when this check fails).

**Comment by russel** [comment]
I agree with the recommendation – actually I thought that was what the tests were doing, but I moved the tests from Python server side to JavaScript client side and so anything could have happened. I'll check and make things as you suggest.

**Comment by russel** [comment]
I think ea315cd198f18623d48ba87c82953b5812864f8d and d22797c6fd643417c0875886cfee56d7b4089fc4 may make this work more as it should.

**Comment by ahtotruu** [comment]
I'm afraid the change has the fields reversed: now the first passphrase field complains when the two entries are not the same and the second one complains when the phrase is too short.

**Comment by russel** [comment]
I believe this may be due to caching in the browser. Chrome and Firefox have this uncanny ability not to update JavaScript and CSS changes. I end up flushing the cache lots with them.

I had to make a change to the data model and so have deployed a new database as well as a new application.

**Comment by ahtotruu** [comment]
Indeed, after flushing the browser cache, now both fields seem to work correctly.
