### ISSUE TITLE
Value of the "country" field of the registration form does not stick

### ISSUE THREAD

**Issue by ahtotruu** [ACCUConf/ACCUConf_Submission_Web_Application#50]

**Comment by russel** [comment]
Not sure what this means. My current hypothesis is that if you try to amend your registration details, the form shows the wrong country.

**Comment by ahtotruu** [comment]
I thought the title says it all an no further description is needed, but indeed, the value given in registration form reverts back to the default on the update form. Without direct database access, can't check if the reason is that the value is not saved to the DB or that it is not read back from the DB.

**Comment by russel** [comment]
As it happens the title did convey the intended point, I just wasn't sure I had inferred correctly.

Thanks for doing these checks and reporting in, it is very appreciated.

**Comment by russel** [comment]
Commit b945cdaa9ce85929acc8098a5df4287a5be6cb8f should fix this and commit cea59288f51a31722d2ae2a5a9055937f0201c24 adds the test that was missing that would have detected this.

**Comment by russel** [comment]
@ahtotruu Has this problem gone away as well?

**Comment by ahtotruu** [comment]
Indeed it has. Forgot that I had created two separate issues for the two forms :)
