### ISSUE TITLE
Several fields of the session proposal form do not stick

### ISSUE THREAD

**Issue by ahtotruu** [ACCUConf/ACCUConf_Submission_Web_Application#51]
The fields are: "session type", "audience", "category".

**Comment by russel** [comment]
So this is on trying to amend a proposal, the values entered (and which are most likely in the database, are not presented in the form.

(Hummm… there should have been a test for that.)

**Comment by ahtotruu** [comment]
Indeed, the values given in submission form revert back to the defaults on the update form. Without direct database access, can't check if the reason is that they are not saved to the DB or that they are not read back from the DB.

**Comment by russel** [comment]
This one was clearly me just forgetting to put this stuff in place. This time I shall write the test first and then do the fix.

**Comment by russel** [comment]
I believe 2590a6a86c5fc343a8b19010f3bbca5aca7c7085 fixes this one. There was a mess of unfinished stuff that I had in my mind was finished. It still isn't totally done, but it is a lot better now than it was. This issues has been most useful!

**Comment by ahtotruu** [comment]
Yes, looks good now.
