### ISSUE TITLE
Confusing bio behaviour

### ISSUE THREAD

**Issue by Gailogail** [ACCUConf/ACCUConf_Submission_Web_Application#54]
Now I can successfully create 2 and more proposals, I find that:

- My existing bio does not appear in the form to be available for editing; this section is blank.

- If I type in a new, too short bio I get a 'problem submitting' message at the top but no warning next to the bio field

- If I type in a new, long enough bio I can then submit. But the bio is not updated; if I view the proposal again I see the original bio.

I think probably if the bio is going to appear on subsequent proposals it should be as an edit, and  should check whether the user wants to change a bio already associated with an existing proposal. I assume each person is allowed only one bio regardless of number of submissions. But they should be allowed to update it if further submissions inspire them to reword it.

**Comment by russel** [comment]
I think I have fixed the second of these three in the update I am just making. No tests. :-(

I agree that the other two issues of the bios are bugs not a confusion.

**Comment by russel** [comment]
I believe I have now fixed the other two points. I will have to admit to not having tests for the two situations as yet, I shall retrofit something, but I haven't broken  any existing tests.

**Comment by Gailogail** [comment]
Tickety and boo-shaped on editing a bio. It now shows me my existing bio in a new proposal, lets me change it and reflects that in other proposals,

If the change is to go too minimalist, I still get "Problem with form, not submitting." without any further information about what the problem is.

**Comment by russel** [comment]
Sponditious, but also ####. I am going to go for writing a test first for this one, which will also cover my #rse for all the changes I made without doing a test first. I haven't a clue why it isn't reporting, it does here – but clearly the context I am creating must be different. I shall take this one away a while.

Thanks massively for trying things out, we have nailed a few points today that would have annoyed a lot of people, and they were relatively small changes that should have been in there months ago.

**Comment by Gailogail** [comment]
Being a marker of programming assignments has evidently given me a talent for finding the weaknesses. Poacher turned well-armed gamekeeper!

**Comment by Gailogail** [comment]
Re. short bio: actual limit it seems to apply is 41 chars, not 50. (The minima for title & summary behave as advertised).

**Comment by russel** [comment]
Oops. That one easily fixed. Sadly there seems to be no way of not having multiple constants for that.

**Comment by russel** [comment]
I am going to close this one as I think it's got a bit amorphous. I believe there may still be problems/bugs, but I think having new issues for them would be the best way forward.
