### ISSUE TITLE
Additional column on the review page

### ISSUE THREAD

**Issue by FelixPetriconi** [ACCUConf/ACCUConf_Submission_Web_Application#61]
It would be great if there is an additional column on review proposals page that indicates in a short term, what kind of session it is.
Since we have this year so many pre-conf proposals and it is not obvious from the title, I would like more easy to go them directly so that I can weight them against each other.

**Comment by russel** [comment]
The type of session is displayed on the current review form, are you thinking that this is in the wrong place? That is easily fixed.

**Comment by russel** [comment]
@FelixPetriconi Can we pick up on this one again, if I can understand whether there is still a problem, now is a good time to fix it.

**Comment by FelixPetriconi** [comment]
I think at that time, I wanted to have the type displayed in the overview of all proposals.

**Comment by russel** [comment]
OK, that makes sense. I can do that fairly quickly, but I am not sure I can do a filter quickly. Once the session type is displayed in the list, we should close this issue and raise a new issue asking for a filter on type.

**Comment by russel** [comment]
I believe this column is now in place. I shall add a new issue about filtering or some such on the field.
