### ISSUE TITLE
Move session type & audience to top

### ISSUE THREAD

**Issue by Gailogail** [ACCUConf/ACCUConf_Submission_Web_Application#72]
Would be good to set the context in which to read the abstract by displaying the session type and audience first.

**Comment by russel** [comment]
Would it be reasonable to deploy a change immediately? I have deployed to cfp.testconference.accu.org for people to see the effect.

**Comment by Gailogail** [comment]
I get 'user/passphrase' not recognised for that one.

**Comment by russel** [comment]
Curses, I am keeping the database there up-to-date with the real one, albeit manually. Let me reset it again.

**Comment by russel** [comment]
@Gailogail Can we pick this point up so as to ensure I fix it before the start of the call for proposals.

**Comment by Gailogail** [comment]
When you say "Can we pick this point up", is there anything I need to do? I see it's still open and tagged as an enhancement.

**Comment by russel** [comment]
I believe this is a completed issue, so I shall close it.
