### ISSUE TITLE
'Pass'

### ISSUE THREAD

**Issue by Gailogail** [ACCUConf/ACCUConf_Submission_Web_Application#73]
There are inevitably some where I don't feel I have enough expertise or interest to give a meaningful score (quite a lot of the C++ ones, frankly). Happy to comment, because I can still form an opinion about the clarity and focus of the abstract and the general depth or breadth of topics. So it would be useful to be able to mark a review as 'done' without a score.

If it's too messy to have comments without scores, it would be useful to have a 'pass' option so that submissions which I'm happy to defer to others about cease to appear on my list as unreviewed.

**Comment by russel** [comment]
Hummm… in my head 0 was not a score, but a pass.  Perhaps this is a poor convention in this context. The difficulty is trying to have good typing of the fields. Perhaps I can try -1 for pass?

**Comment by Gailogail** [comment]
I'm OK with a 1-10 where 1 is 'not on your Nelly'. So long as (a)  your calculations omit the 0s and (b) the reviewer interface states that 0 means pass. I do need it on screen when reviewing; can't depend on me correctly remembering the interpretation of the numbers and in any case we need to be sure we are all following the same convention. Although for that reason, actually, I'd prefer a 'pass' button (don't care how it's encoded under the covers) so that it's explicitly a different choice, not possible to confuse with giving a low score.

**Comment by russel** [comment]
I will check, but I believe the mean and median calculations do ignore 0s. Clearly I failed to provide a webpage of instructions to reviewing. Certainly it is possible to add a new button for 0 and have the score 1..10 for the score button. Just not in the next day or two, so for next year. Does that work for you?

**Comment by Gailogail** [comment]
Next year's fine. But with the meaning clear on the review page wherever possible, rather than (or in additio to) separate instructions.

**Comment by russel** [comment]
It appears zeros were included in the statistics. I shall remove this. Then we can have 0 for pass and 1..10 as an active score.
